### ISSUE TITLE
Провести проверку на большом файле

### ISSUE THREAD

**Issue by alexkoss** [SergeiYelnitski/Lng#1]
Добрый день! Меня зовут Александр, представитель компании БалтИнфоКом.

Предлагаю осуществить проверку на большом файле.

Файл: https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

В ответе должно быть количество групп и время выполнения.

**Comment by SergeiYelnitski** [comment]
Число групп с более чем одним элементом: 105036
Время выполнения = 6.224 сек

выводит это, но, видимо, это не правильно
